// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZTm-UMHWv0hJl_srGjWyahNNJTcUE0ck',
    appId: '1:127452184188:web:7f870045240a899dc013f9',
    messagingSenderId: '127452184188',
    projectId: 'notes-32e49',
    authDomain: 'notes-32e49.firebaseapp.com',
    storageBucket: 'notes-32e49.appspot.com',
    measurementId: 'G-JXD0QHDBTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNw9msA97pJFIpN3nq8Y_ETHZMIgTGclI',
    appId: '1:127452184188:android:b97b80b003577b32c013f9',
    messagingSenderId: '127452184188',
    projectId: 'notes-32e49',
    storageBucket: 'notes-32e49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnuG_vs78E90P8y8xznIWV8H69k9Lq2xo',
    appId: '1:127452184188:ios:dcffba857f42a42bc013f9',
    messagingSenderId: '127452184188',
    projectId: 'notes-32e49',
    storageBucket: 'notes-32e49.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnuG_vs78E90P8y8xznIWV8H69k9Lq2xo',
    appId: '1:127452184188:ios:48a2ab7929d14b8ec013f9',
    messagingSenderId: '127452184188',
    projectId: 'notes-32e49',
    storageBucket: 'notes-32e49.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
